"""
Generate the BE552 / EC552 final-project report PDF for BioPilot.

Targets the deliverable layout (2-3 pages):
- Team + project description
- 1-3 lines per major component (Knox, MCPGeneBank, generative-syn-bio)
- Compile / run notes

Output:
    Final Project BioPilot/BioPilot Final Project Report.pdf
"""
from __future__ import annotations

from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)


HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
OUT = ROOT / "Final Project BioPilot" / "BioPilot Final Project Report.pdf"


def build():
    doc = SimpleDocTemplate(
        str(OUT),
        pagesize=LETTER,
        leftMargin=0.7 * inch,
        rightMargin=0.7 * inch,
        topMargin=0.7 * inch,
        bottomMargin=0.7 * inch,
        title="BioPilot — Final Project Report",
        author="BioPilot Team",
    )
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("H1", parent=styles["Heading1"], spaceAfter=8, fontSize=18)
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], spaceAfter=6, fontSize=13)
    body = ParagraphStyle("Body", parent=styles["BodyText"], leading=14, spaceAfter=6, fontSize=10)
    bold = ParagraphStyle("Bold", parent=body, fontName="Helvetica-Bold")
    mono = ParagraphStyle(
        "Mono", parent=body, fontName="Courier", fontSize=9, leading=11, leftIndent=12
    )

    story = []

    # ── Header ──────────────────────────────────────────────────────
    story.append(Paragraph("BioPilot", h1))
    story.append(
        Paragraph(
            "<i>End-to-End Generative Design and Evolution of Synthetic Biology Designs</i>",
            body,
        )
    )
    story.append(Paragraph("BE552 / EC552 Final Project Report — Spring 2026", body))
    story.append(Spacer(1, 8))

    team_tbl = Table(
        [
            ["Team:", "BioPilot"],
            ["Members:", "Charles Van Hook, Joshua Kome, Michael Wallace"],
            ["Repository:", "https://github.com/mswallac/BE552_Project"],
        ],
        colWidths=[1.3 * inch, 5.5 * inch],
    )
    team_tbl.setStyle(
        TableStyle(
            [
                ("FONT", (0, 0), (0, -1), "Helvetica-Bold", 10),
                ("FONT", (1, 0), (1, -1), "Helvetica", 10),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
            ]
        )
    )
    story.append(team_tbl)
    story.append(Spacer(1, 12))

    # ── Project description ─────────────────────────────────────────
    story.append(Paragraph("Project Description", h2))
    story.append(
        Paragraph(
            "BioPilot is an integrated platform that turns a natural-language design "
            "request (e.g. <i>“design an arsenic biosensor that produces GFP”</i>) into "
            "a sequence-resolved, combinatorially enumerable genetic-circuit design "
            "space. A Gemini 2.5 LLM agent orchestrates real biological parts pulled "
            "via MCP from a curated ~750-part database (Cello UCFs + iGEM canonicals + "
            "iGEM-distribution kit + UniProt), assembles them into a GOLDBAR design "
            "space stored in Neo4j, and exposes the full enumeration through a web UI. "
            "Once a design is enumerated, individual DNA slots can be regenerated by "
            "NVIDIA's hosted Evo 2 40B foundation model using the upstream 5' context, "
            "and the (possibly edited) construct can be exported as a GenBank file.",
            body,
        )
    )

    # ── Major software components ───────────────────────────────────
    story.append(Spacer(1, 4))
    story.append(Paragraph("Major Software Components", h2))

    comp_tbl = Table(
        [
            [
                Paragraph("<b>Knox</b><br/><font size='8' color='#666'>Java / Spring Boot</font>", body),
                Paragraph(
                    "LLM agent (Gemini 2.5) with the MCP client; GOLDBAR-based "
                    "combinatorial design DSL; Neo4j-backed design-space repository; "
                    "Sequence Viewer modal with per-slot Evo 2 regenerate and GenBank "
                    "export. Serves the demo UI at <font face='Courier'>localhost:8080</font>.",
                    body,
                ),
            ],
            [
                Paragraph(
                    "<b>MCPGeneBank</b><br/><font size='8' color='#666'>Python / FastMCP / Qdrant</font>",
                    body,
                ),
                Paragraph(
                    "Curated parts database exposed as an MCP server. Vector search "
                    "via Qdrant + sentence-transformers, with an exact-ID fast-path "
                    "so canonical accessions (BBa_R0040, P03038, …) reliably resolve "
                    "regardless of embedding-similarity noise. Tools: "
                    "<font face='Courier'>search_parts</font>, "
                    "<font face='Courier'>search_parts_batch</font>, "
                    "<font face='Courier'>get_part</font>, "
                    "<font face='Courier'>get_parts_batch</font>.",
                    body,
                ),
            ],
            [
                Paragraph(
                    "<b>generative-syn-bio</b><br/><font size='8' color='#666'>Python / PyTorch / Evo 2</font>",
                    body,
                ),
                Paragraph(
                    "Local Evo 2 generative pipeline: Cello UCF parser, multi-objective "
                    "scorer (GC, MFE, Shine-Dalgarno, sequence perplexity), "
                    "<font face='Courier'>PartSpec</font> Pydantic schema. The live "
                    "demo uses NVIDIA's hosted Evo 2 NIM rather than this local stack, "
                    "but the local pipeline is included for offline scoring and ablation.",
                    body,
                ),
            ],
            [
                Paragraph(
                    "<b>Evo 2 NIM client</b><br/><font size='8' color='#666'>NVIDIA-hosted REST</font>",
                    body,
                ),
                Paragraph(
                    "Inside Knox, a thin <font face='Courier'>Evo2Service</font> "
                    "calls <font face='Courier'>build.nvidia.com/arc/evo2-40b/generate</font> "
                    "with a 5' DNA context and the requested token count, returns the "
                    "generated extension and mean sampled probability. Single-retry on "
                    "transient 5xx so the demo isn't fragile against gateway hiccups.",
                    body,
                ),
            ],
        ],
        colWidths=[1.4 * inch, 5.4 * inch],
    )
    comp_tbl.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("LINEBELOW", (0, 0), (-1, -2), 0.5, colors.HexColor("#cccccc")),
            ]
        )
    )
    story.append(comp_tbl)
    story.append(Spacer(1, 8))

    # ── Page 2: install + build + run ───────────────────────────────
    story.append(Paragraph("Compile, Build &amp; Run Notes", h2))

    story.append(Paragraph("<b>System dependencies</b>", body))
    story.append(
        Paragraph(
            "Docker Desktop ≥ 4.0 (with Docker Compose v2); "
            "Anaconda or system Python 3.11+ (the MCP server runs on the host so the "
            "Knox container can reach it via <font face='Courier'>host.docker.internal</font>); "
            "Java JDK 17 + Maven 3.9 only if you choose to run Knox without Docker.",
            body,
        )
    )

    story.append(Paragraph("<b>API keys</b> (placed in Knox's <font face='Courier'>.env</font>, gitignored)", body))
    api_tbl = Table(
        [
            ["Variable", "Required for", "Source"],
            ["GEMINI_API_KEY", "Knox LLM agent", "ai.google.dev (free tier)"],
            ["NVIDIA_API_KEY", "Sequence Viewer Evo 2 fill", "build.nvidia.com/arc/evo2-40b"],
            ["OPENAI_API_KEY / CLAUDE_API_KEY", "Optional alternate LLM providers", "openai.com / anthropic.com"],
            ["HF_TOKEN", "Optional — local generative-syn-bio Evo 2", "huggingface.co"],
        ],
        colWidths=[1.7 * inch, 2.6 * inch, 2.4 * inch],
    )
    api_tbl.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eeeeee")),
                ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 9),
                ("FONT", (0, 1), (-1, -1), "Helvetica", 9),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#bbbbbb")),
            ]
        )
    )
    story.append(api_tbl)
    story.append(Spacer(1, 6))

    story.append(Paragraph("<b>Build / run sequence</b>", body))
    cmds = [
        "# 1. Clone with submodules",
        "git clone --recurse-submodules https://github.com/mswallac/BE552_Project.git",
        "cd BE552_Project",
        "",
        "# 2. (One-time) install Python deps + build the parts DB (~5-10 min)",
        'cd "Final Project BioPilot/Code/MCPGeneBank/bio-circuit-ai"',
        "pip install -r requirements.txt",
        "python scrape_clean.py",
        "cd ../../../..",
        "",
        "# 3. Set API keys in",
        "#   Final Project BioPilot/Code/Knox_BE552/knox-master/.env",
        "",
        "# 4. Terminal 1 — start MCP server on the host",
        "python scripts/run_mcpgenebank_mcp.py",
        "",
        "# 5. Terminal 2 — start Knox + Neo4j",
        'cd "Final Project BioPilot/Code/Knox_BE552/knox-master"',
        "docker-compose up --build",
        "",
        "# Open http://localhost:8080 and try a design prompt.",
    ]
    for line in cmds:
        story.append(Paragraph(line.replace(" ", "&nbsp;") or "&nbsp;", mono))

    story.append(Spacer(1, 6))
    story.append(Paragraph("<b>Verifying the install</b>", body))
    smoke = [
        "curl -s -o /dev/null -w 'MCP=%{http_code}\\n' http://localhost:8000/sse",
        "curl -s -o /dev/null -w 'Knox=%{http_code}\\n' http://localhost:8080/",
        "curl -s -X POST 'http://localhost:8080/agent?prompt=design+an+arsenic+biosensor+that+produces+GFP' --max-time 180",
    ]
    for line in smoke:
        story.append(Paragraph(line.replace(" ", "&nbsp;"), mono))

    story.append(Spacer(1, 6))
    story.append(Paragraph("<b>Demo prompts known to work</b>", body))
    prompts = [
        "design an arsenic biosensor that produces GFP",
        "make me a blue-green oscillator repressilator",
        "design a genetic toggle switch with LacI and TetR, one state glows red the other green",
        "design a circuit where arabinose induces GFP expression",
        "make five constitutive promoter variants driving GFP at different strengths",
    ]
    for p in prompts:
        story.append(Paragraph("• " + p, body))

    story.append(Spacer(1, 6))
    story.append(Paragraph("<b>Repository layout</b>", body))
    layout = [
        "BE552_Project/",
        "  README.md                       # full install / dependencies / run guide",
        "  scripts/                        # MCP launcher + parts-sync utilities",
        "  Final Project BioPilot/         # graded deliverable folder",
        "      BioPilot Final Project Report.pdf",
        "      Code/",
        "          README.md               # index of the three sub-projects",
        "          Knox_BE552/             # Java / Spring Boot - LLM, GOLDBAR, UI, Evo 2 fill",
        "          MCPGeneBank/            # Python - parts DB + MCP server (submodule)",
        "          generative-syn-bio/     # Python - local Evo 2 + scorer (submodule)",
    ]
    for line in layout:
        story.append(Paragraph(line.replace(" ", "&nbsp;"), mono))

    story.append(Spacer(1, 6))
    story.append(
        Paragraph(
            "Code is commented throughout; entry points and important annotations "
            "are listed in <font face='Courier'>Final Project BioPilot/Code/README.md</font>.",
            body,
        )
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    doc.build(story)
    print(f"Wrote {OUT}  ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    build()
